ALTER TABLE "registros_atividade" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "log_auditoria" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "links_coleta" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "eventos_contrato" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "templates_contrato" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "contratos" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "documentos" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "notificacoes" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "organizacoes" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "pessoas" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "regioes" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "usuarios" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "contratos" ADD COLUMN "regiao_id" uuid;--> statement-breakpoint
ALTER TABLE "documentos" ADD COLUMN "regiao_id" uuid;--> statement-breakpoint
ALTER TABLE "contratos" ADD CONSTRAINT "contratos_regiao_id_regioes_id_fk" FOREIGN KEY ("regiao_id") REFERENCES "public"."regioes"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "documentos" ADD CONSTRAINT "documentos_regiao_id_regioes_id_fk" FOREIGN KEY ("regiao_id") REFERENCES "public"."regioes"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE POLICY "registros_atividade_organizacao_regiao" ON "registros_atividade" AS PERMISSIVE FOR ALL TO "authenticated" USING ("registros_atividade"."organizacao_id" = (select auth.organizacao_id()) AND ((select auth.papel()) <> 'coord_regiao' OR "registros_atividade"."regiao_id" = (select auth.regiao_id()))) WITH CHECK ("registros_atividade"."organizacao_id" = (select auth.organizacao_id()) AND ((select auth.papel()) <> 'coord_regiao' OR "registros_atividade"."regiao_id" = (select auth.regiao_id())));--> statement-breakpoint
CREATE POLICY "registros_atividade_mfa" ON "registros_atividade" AS RESTRICTIVE FOR ALL TO "authenticated" USING ((select auth.papel()) NOT IN ('gestor', 'coord_comite') OR ((select auth.jwt()) ->> 'aal') = 'aal2') WITH CHECK ((select auth.papel()) NOT IN ('gestor', 'coord_comite') OR ((select auth.jwt()) ->> 'aal') = 'aal2');--> statement-breakpoint
CREATE POLICY "log_auditoria_organizacao_select" ON "log_auditoria" AS PERMISSIVE FOR SELECT TO "authenticated" USING ("log_auditoria"."organizacao_id" = (select auth.organizacao_id()));--> statement-breakpoint
CREATE POLICY "log_auditoria_organizacao_insert" ON "log_auditoria" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ("log_auditoria"."organizacao_id" = (select auth.organizacao_id()));--> statement-breakpoint
CREATE POLICY "log_auditoria_mfa" ON "log_auditoria" AS RESTRICTIVE FOR ALL TO "authenticated" USING ((select auth.papel()) NOT IN ('gestor', 'coord_comite') OR ((select auth.jwt()) ->> 'aal') = 'aal2') WITH CHECK ((select auth.papel()) NOT IN ('gestor', 'coord_comite') OR ((select auth.jwt()) ->> 'aal') = 'aal2');--> statement-breakpoint
CREATE POLICY "links_coleta_organizacao" ON "links_coleta" AS PERMISSIVE FOR ALL TO "authenticated" USING ("links_coleta"."organizacao_id" = (select auth.organizacao_id())) WITH CHECK ("links_coleta"."organizacao_id" = (select auth.organizacao_id()));--> statement-breakpoint
CREATE POLICY "links_coleta_mfa" ON "links_coleta" AS RESTRICTIVE FOR ALL TO "authenticated" USING ((select auth.papel()) NOT IN ('gestor', 'coord_comite') OR ((select auth.jwt()) ->> 'aal') = 'aal2') WITH CHECK ((select auth.papel()) NOT IN ('gestor', 'coord_comite') OR ((select auth.jwt()) ->> 'aal') = 'aal2');--> statement-breakpoint
CREATE POLICY "eventos_contrato_organizacao_select" ON "eventos_contrato" AS PERMISSIVE FOR SELECT TO "authenticated" USING (exists (select 1 from contratos c where c.id = "eventos_contrato"."contrato_id" and c.organizacao_id = (select auth.organizacao_id())));--> statement-breakpoint
CREATE POLICY "eventos_contrato_organizacao_insert" ON "eventos_contrato" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (exists (select 1 from contratos c where c.id = "eventos_contrato"."contrato_id" and c.organizacao_id = (select auth.organizacao_id())));--> statement-breakpoint
CREATE POLICY "eventos_contrato_mfa" ON "eventos_contrato" AS RESTRICTIVE FOR ALL TO "authenticated" USING ((select auth.papel()) NOT IN ('gestor', 'coord_comite') OR ((select auth.jwt()) ->> 'aal') = 'aal2') WITH CHECK ((select auth.papel()) NOT IN ('gestor', 'coord_comite') OR ((select auth.jwt()) ->> 'aal') = 'aal2');--> statement-breakpoint
CREATE POLICY "templates_contrato_organizacao" ON "templates_contrato" AS PERMISSIVE FOR ALL TO "authenticated" USING ("templates_contrato"."organizacao_id" = (select auth.organizacao_id())) WITH CHECK ("templates_contrato"."organizacao_id" = (select auth.organizacao_id()));--> statement-breakpoint
CREATE POLICY "templates_contrato_mfa" ON "templates_contrato" AS RESTRICTIVE FOR ALL TO "authenticated" USING ((select auth.papel()) NOT IN ('gestor', 'coord_comite') OR ((select auth.jwt()) ->> 'aal') = 'aal2') WITH CHECK ((select auth.papel()) NOT IN ('gestor', 'coord_comite') OR ((select auth.jwt()) ->> 'aal') = 'aal2');--> statement-breakpoint
CREATE POLICY "contratos_organizacao_regiao" ON "contratos" AS PERMISSIVE FOR ALL TO "authenticated" USING ("contratos"."organizacao_id" = (select auth.organizacao_id()) AND ((select auth.papel()) <> 'coord_regiao' OR "contratos"."regiao_id" = (select auth.regiao_id()))) WITH CHECK ("contratos"."organizacao_id" = (select auth.organizacao_id()) AND ((select auth.papel()) <> 'coord_regiao' OR "contratos"."regiao_id" = (select auth.regiao_id())));--> statement-breakpoint
CREATE POLICY "contratos_mfa" ON "contratos" AS RESTRICTIVE FOR ALL TO "authenticated" USING ((select auth.papel()) NOT IN ('gestor', 'coord_comite') OR ((select auth.jwt()) ->> 'aal') = 'aal2') WITH CHECK ((select auth.papel()) NOT IN ('gestor', 'coord_comite') OR ((select auth.jwt()) ->> 'aal') = 'aal2');--> statement-breakpoint
CREATE POLICY "documentos_organizacao_regiao" ON "documentos" AS PERMISSIVE FOR ALL TO "authenticated" USING ("documentos"."organizacao_id" = (select auth.organizacao_id()) AND ((select auth.papel()) <> 'coord_regiao' OR "documentos"."regiao_id" = (select auth.regiao_id()))) WITH CHECK ("documentos"."organizacao_id" = (select auth.organizacao_id()) AND ((select auth.papel()) <> 'coord_regiao' OR "documentos"."regiao_id" = (select auth.regiao_id())));--> statement-breakpoint
CREATE POLICY "documentos_mfa" ON "documentos" AS RESTRICTIVE FOR ALL TO "authenticated" USING ((select auth.papel()) NOT IN ('gestor', 'coord_comite') OR ((select auth.jwt()) ->> 'aal') = 'aal2') WITH CHECK ((select auth.papel()) NOT IN ('gestor', 'coord_comite') OR ((select auth.jwt()) ->> 'aal') = 'aal2');--> statement-breakpoint
CREATE POLICY "notificacoes_organizacao" ON "notificacoes" AS PERMISSIVE FOR ALL TO "authenticated" USING ("notificacoes"."organizacao_id" = (select auth.organizacao_id())) WITH CHECK ("notificacoes"."organizacao_id" = (select auth.organizacao_id()));--> statement-breakpoint
CREATE POLICY "notificacoes_mfa" ON "notificacoes" AS RESTRICTIVE FOR ALL TO "authenticated" USING ((select auth.papel()) NOT IN ('gestor', 'coord_comite') OR ((select auth.jwt()) ->> 'aal') = 'aal2') WITH CHECK ((select auth.papel()) NOT IN ('gestor', 'coord_comite') OR ((select auth.jwt()) ->> 'aal') = 'aal2');--> statement-breakpoint
CREATE POLICY "organizacoes_select" ON "organizacoes" AS PERMISSIVE FOR SELECT TO "authenticated" USING ("organizacoes"."id" = (select auth.organizacao_id()));--> statement-breakpoint
CREATE POLICY "organizacoes_mfa" ON "organizacoes" AS RESTRICTIVE FOR ALL TO "authenticated" USING ((select auth.papel()) NOT IN ('gestor', 'coord_comite') OR ((select auth.jwt()) ->> 'aal') = 'aal2') WITH CHECK ((select auth.papel()) NOT IN ('gestor', 'coord_comite') OR ((select auth.jwt()) ->> 'aal') = 'aal2');--> statement-breakpoint
CREATE POLICY "pessoas_organizacao_regiao" ON "pessoas" AS PERMISSIVE FOR ALL TO "authenticated" USING ("pessoas"."organizacao_id" = (select auth.organizacao_id()) AND ((select auth.papel()) <> 'coord_regiao' OR "pessoas"."regiao_id" = (select auth.regiao_id()))) WITH CHECK ("pessoas"."organizacao_id" = (select auth.organizacao_id()) AND ((select auth.papel()) <> 'coord_regiao' OR "pessoas"."regiao_id" = (select auth.regiao_id())));--> statement-breakpoint
CREATE POLICY "pessoas_mfa" ON "pessoas" AS RESTRICTIVE FOR ALL TO "authenticated" USING ((select auth.papel()) NOT IN ('gestor', 'coord_comite') OR ((select auth.jwt()) ->> 'aal') = 'aal2') WITH CHECK ((select auth.papel()) NOT IN ('gestor', 'coord_comite') OR ((select auth.jwt()) ->> 'aal') = 'aal2');--> statement-breakpoint
CREATE POLICY "regioes_select" ON "regioes" AS PERMISSIVE FOR SELECT TO "authenticated" USING ("regioes"."organizacao_id" = (select auth.organizacao_id()));--> statement-breakpoint
CREATE POLICY "regioes_mfa" ON "regioes" AS RESTRICTIVE FOR ALL TO "authenticated" USING ((select auth.papel()) NOT IN ('gestor', 'coord_comite') OR ((select auth.jwt()) ->> 'aal') = 'aal2') WITH CHECK ((select auth.papel()) NOT IN ('gestor', 'coord_comite') OR ((select auth.jwt()) ->> 'aal') = 'aal2');--> statement-breakpoint
CREATE POLICY "usuarios_organizacao" ON "usuarios" AS PERMISSIVE FOR ALL TO "authenticated" USING ("usuarios"."organizacao_id" = (select auth.organizacao_id())) WITH CHECK ("usuarios"."organizacao_id" = (select auth.organizacao_id()));--> statement-breakpoint
CREATE POLICY "usuarios_mfa" ON "usuarios" AS RESTRICTIVE FOR ALL TO "authenticated" USING ((select auth.papel()) NOT IN ('gestor', 'coord_comite') OR ((select auth.jwt()) ->> 'aal') = 'aal2') WITH CHECK ((select auth.papel()) NOT IN ('gestor', 'coord_comite') OR ((select auth.jwt()) ->> 'aal') = 'aal2');